import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import MoviesList from "@/app/(way)/genre/movie/list/page";
import Head from "next/head";
import '../moduleCSS/globals.css';
import ThemeToggle from "@/component/ThemeToggle";


// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <Head>
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png"/>
          <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png"/>
          <link rel="manifest" href="/favicon/site.webmanifest"/>
      </Head>
      <body className = 'div_body'>
      <div className='div_gallery'>
          <header>
              <div>
                  <h1 className='h1_layout'>MOVIE</h1>
                  <ThemeToggle />
              </div>
              <nav className='div_genres'>
                  <MoviesList/>
              </nav>
          </header>
          <div className='div_children'>
              {children}
          </div>
      </div>
      </body>
      </html>
  );
}

