import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import style from "@/moduleCSS/style.module.css";
import MoviesList from "@/app/(way)/genre/movie/list/page";
import Head from "next/head";


// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={style.div_body}>
      <div className={style.div_gallery}>
          <header>
              <div>
                  <h1 className={style.h1_layout}>MOVIE</h1>
              </div>
              <nav className={style.div_genres}>
                  <MoviesList/>
              </nav>
          </header>
          <div className={style.div_children}>
              {children}
          </div>
      </div>
      </body>
      </html>
  );
}

